package kalaha;

import java.awt.*;
import javax.swing.JOptionPane;

/**
 *
 * @author henri
 */
public class SpillepladePanel extends javax.swing.JPanel
{    
    private Kalaha kalaha;
    private KalahaSpilleplade kalahaspilleplade;
    
    /**
     * Creates new form SpillepladePanel
     */
    public SpillepladePanel(String[] IP)
    {
	try
	{
	    kalahaspilleplade = new KalahaSpilleplade(2, 6, 0, IP, 41970);
	}
	catch (Exception e)
	{
	    JOptionPane.showMessageDialog(null,"Én eller flere af de indtastede IP addresser er ikke gyldig.");
	    e.printStackTrace();
	}
	
	initComponents();
    }
    
    public void paintComponent(Graphics g)
    {
	super.paintComponent(g);
	Graphics2D g2 = (Graphics2D) g;
        
        // Tegn bræt
        g2.setColor(new Color(193, 154, 107));
        g2.fill3DRect(25,100,1500,380,true);
        
	g2.setFont(new Font("Arial", Font.PLAIN, 20));
	
	int j = 13;
	int k = 1;
	for (int i = 0; i < 6; i++)
	{
	    g2.setColor(new Color(134, 101, 56));
	    g2.fillOval(225+i*185,295,175,175);		// Nederste række
	    g2.fillOval(225+i*185,110,175,175);		// Øverste række
	    
	    // Tegn kugler og antal i hullerne
	    g2.setColor(new Color(36, 28, 19));
	    g2.fillOval(225+i*185+54,295+77,25,25);	// Nederste række
	    g2.drawString("X " + kalahaspilleplade.getHul(k).getAntalKugler(),225+i*185+84,295+97);
	    g2.fillOval(225+i*185+54,110+77,25,25);	// Øverste række
	    g2.drawString("X " + kalahaspilleplade.getHul(j).getAntalKugler(),225+i*185+84,110+97);
	    j--;
	    k++;
	}
	
        for (int i = 0; i <= 37; i++)
        {
            // Tegn mål huller
            g2.setColor(new Color(134, 101, 56));
            g2.fillOval(40,110+5*i,175,175);            // Venstre mål
            g2.fillOval(1335,110+5*i,175,175);          // Højre mål
        }
	
        // Tegn kugler og antal i målene
        g2.setColor(new Color(36, 28, 19));
        g2.fillOval(40+54,275,25,25);								// Venstre mål
        g2.drawString("X " + kalahaspilleplade.getHul(14).getAntalKugler(),40+84,295);
	g2.fillOval(1335+54,275,25,25);								// Højre mål
	g2.drawString("X " + kalahaspilleplade.getHul(7).getAntalKugler(),1335+84,295);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                formMouseClicked(evt);
            }
        });

        jLabel2.setText("Spiller 1:");
        jLabel2.setText("Spiller 1: " + kalahaspilleplade.getHul(7).getAntalKugler() + " point");

        jLabel3.setText("Spiller 2:");
        jLabel3.setText("Spiller 2: " + kalahaspilleplade.getHul(14).getAntalKugler() + " point");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(607, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(256, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_formMouseClicked
    {//GEN-HEADEREND:event_formMouseClicked
        // Udregning af simple koordinaterne som et 8x2 gitter
	int x = Math.round((evt.getX() - 25)/(1500/8));
        int y = Math.round((evt.getY() - 100)/(380/2));
        
	System.out.println(x + "," + y);
	
	if (y == 1)
	{
	    if (x > 0 && x < 7)
	    {
		System.out.println("Du har trykket på dit eget hul (hehe) nr: " + x);
	    }
	}
    }//GEN-LAST:event_formMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
